// // FILE: services/api-server/src/routes/internal.ts

// import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
// import { sendSignalPushNotifications } from './notifications';
// import supabase from '../db/supabase';
// import { SMCSignal } from '../models/signal';
// import { broadcastSignal } from '../ws/signal_broadcaster';

// const INTERNAL_SECRET = process.env.INTERNAL_SECRET ?? 'changeme';

// export async function internalRoutes(fastify: FastifyInstance) {

//   // ── POST /internal/signal ───────────────────────────────────
//   // Called by the Python signal engine when a new signal is generated.
//   // Saves signal to Supabase, broadcasts via WebSocket, and sends FCM push.

//   fastify.post('/internal/signal', async (req: FastifyRequest, reply: FastifyReply) => {
//     const secret = req.headers['x-internal-secret'];
//     if (secret !== INTERNAL_SECRET) {
//       return reply.status(403).send({ error: 'Forbidden' });
//     }

//     const signal = req.body as Partial<SMCSignal>;

//     if (!signal.pair || !signal.type || signal.entry == null) {
//       return reply.status(400).send({ error: 'Missing required signal fields (pair, type, entry)' });
//     }

//     console.log(`[Internal] Signal received: ${signal.pair} ${signal.type} conf=${signal.confidence_score}%`);

//     // 1. Save signal to Supabase
//     const { data: saved, error: dbError } = await supabase
//       .from('signals')
//       .insert({
//         pair:             signal.pair,
//         type:             signal.type,
//         entry:            signal.entry,
//         stop_loss:        signal.stop_loss,
//         take_profit:      signal.take_profit,
//         risk_reward:      signal.risk_reward,
//         confidence_score: signal.confidence_score,
//         confluences:      signal.confluences ?? [],
//         htf_bias:         signal.htf_bias,
//         entry_model:      signal.entry_model,
//         timeframe:        signal.timeframe,
//         htf_timeframe:    signal.htf_timeframe,
//         // FIX: persist the real AI explanation generated by the signal engine
//         ai_explanation:   signal.ai_explanation ?? '',
//         signal_time:      new Date().toISOString(),
//       })
//       .select()
//       .single();

//     if (dbError) {
//       console.error('[Internal] DB error:', dbError);
//       return reply.status(500).send({ error: 'Failed to save signal', detail: dbError.message });
//     }

//     const signalId = saved.id;
//     console.log(`[Internal] Signal saved: ${signalId}`);

//     // 2. Map DB row to SMCSignal shape
//     const signalForClients: SMCSignal = {
//       signal_id:        saved.id,
//       pair:             saved.pair,
//       type:             saved.type,
//       entry:            saved.entry,
//       stop_loss:        saved.stop_loss,
//       take_profit:      saved.take_profit,
//       risk_reward:      saved.risk_reward,
//       confidence_score: saved.confidence_score,
//       confluences:      saved.confluences ?? [],
//       htf_bias:         saved.htf_bias,
//       entry_model:      saved.entry_model,
//       ai_explanation:   saved.ai_explanation ?? '',
//       timeframe:        saved.timeframe,
//       htf_timeframe:    saved.htf_timeframe,
//       timestamp:        new Date(saved.signal_time).getTime(),
//     };

//     // 3. FIX: Broadcast via WebSocket to all connected clients FIRST (real-time).
//     // Previously signals only arrived via push notifications — connected clients
//     // had to wait for the next poll. Now they get the signal instantly via WS.
//     try {
//       broadcastSignal(signalForClients);
//       console.log(`[Internal] WS broadcast sent for signal: ${signalId}`);
//     } catch (wsErr) {
//       console.error('[Internal] WS broadcast error:', wsErr);
//     }

//     // 4. Send Expo push notifications for offline/background users
//     let pushed = 0;
//     try {
//       await sendSignalPushNotifications(signalForClients);
//       pushed = 1;
//       console.log(`[Internal] Push notifications sent for signal: ${signalId}`);
//     } catch (pushErr) {
//       console.error('[Internal] Push notification error:', pushErr);
//     }

//     return reply.send({ signal: signalForClients, pushed });
//   });

//   // ── GET /internal/health ────────────────────────────────────

//   fastify.get('/internal/health', async (_req: FastifyRequest, reply: FastifyReply) => {
//     return reply.send({
//       status:    'ok',
//       service:   'smc-api-server',
//       timestamp: Date.now(),
//     });
//   });
// }











// FILE: services/api-server/src/routes/internal.ts
// FIX: Deduplication — reject signals for the same pair+entry seen within
// the last 5 minutes. This prevents burst duplicates on engine restart
// from flooding the DB and the app.

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { sendSignalPushNotifications } from './notifications';
import supabase from '../db/supabase';
import { SMCSignal } from '../models/signal';
import { broadcastSignal } from '../ws/signal_broadcaster';

const INTERNAL_SECRET = process.env.INTERNAL_SECRET ?? 'changeme';

// In-memory dedup cache: "PAIR:ENTRY" → timestamp of last accepted signal
// Clears itself automatically — entries expire after DEDUP_WINDOW_MS
const recentSignals = new Map<string, number>();
const DEDUP_WINDOW_MS = 5 * 60 * 1000; // 5 minutes

function isDuplicate(pair: string, entry: number): boolean {
  const key = `${pair}:${entry}`;
  const last = recentSignals.get(key);
  if (last && Date.now() - last < DEDUP_WINDOW_MS) return true;
  recentSignals.set(key, Date.now());
  // Prune stale entries to prevent memory leak
  if (recentSignals.size > 500) {
    const cutoff = Date.now() - DEDUP_WINDOW_MS;
    for (const [k, ts] of recentSignals.entries()) {
      if (ts < cutoff) recentSignals.delete(k);
    }
  }
  return false;
}

export async function internalRoutes(fastify: FastifyInstance) {

  // ── POST /internal/signal ───────────────────────────────────
  // Called by the Python signal engine when a new signal is generated.
  // Saves signal to Supabase, broadcasts via WebSocket, and sends FCM push.

  fastify.post('/internal/signal', async (req: FastifyRequest, reply: FastifyReply) => {
    const secret = req.headers['x-internal-secret'];
    if (secret !== INTERNAL_SECRET) {
      return reply.status(403).send({ error: 'Forbidden' });
    }

    const signal = req.body as Partial<SMCSignal>;

    if (!signal.pair || !signal.type || signal.entry == null) {
      return reply.status(400).send({ error: 'Missing required signal fields (pair, type, entry)' });
    }

    // FIX: Dedup check — drop signals for the same pair+entry within 5 min
    if (isDuplicate(signal.pair, signal.entry)) {
      console.log(`[Internal] Duplicate suppressed: ${signal.pair} ${signal.type} @ ${signal.entry}`);
      return reply.send({ signal: null, pushed: 0, duplicate: true });
    }

    console.log(`[Internal] Signal received: ${signal.pair} ${signal.type} conf=${signal.confidence_score}%`);

    // 1. Save signal to Supabase
    const { data: saved, error: dbError } = await supabase
      .from('signals')
      .insert({
        pair:             signal.pair,
        type:             signal.type,
        entry:            signal.entry,
        stop_loss:        signal.stop_loss,
        take_profit:      signal.take_profit,
        risk_reward:      signal.risk_reward,
        confidence_score: signal.confidence_score,
        confluences:      signal.confluences ?? [],
        htf_bias:         signal.htf_bias,
        entry_model:      signal.entry_model,
        timeframe:        signal.timeframe,
        htf_timeframe:    signal.htf_timeframe,
        ai_explanation:   signal.ai_explanation ?? '',
        signal_time:      new Date().toISOString(),
      })
      .select()
      .single();

    if (dbError) {
      console.error('[Internal] DB error:', dbError);
      return reply.status(500).send({ error: 'Failed to save signal', detail: dbError.message });
    }

    const signalId = saved.id;
    console.log(`[Internal] Signal saved: ${signalId}`);

    // 2. Map DB row to SMCSignal shape
    const signalForClients: SMCSignal = {
      signal_id:        saved.id,
      pair:             saved.pair,
      type:             saved.type,
      entry:            saved.entry,
      stop_loss:        saved.stop_loss,
      take_profit:      saved.take_profit,
      risk_reward:      saved.risk_reward,
      confidence_score: saved.confidence_score,
      confluences:      saved.confluences ?? [],
      htf_bias:         saved.htf_bias,
      entry_model:      saved.entry_model,
      ai_explanation:   saved.ai_explanation ?? '',
      timeframe:        saved.timeframe,
      htf_timeframe:    saved.htf_timeframe,
      timestamp:        new Date(saved.signal_time).getTime(),
    };

    // 3. Broadcast via WebSocket to all connected clients FIRST (real-time)
    try {
      broadcastSignal(signalForClients);
      console.log(`[Internal] WS broadcast sent for signal: ${signalId}`);
    } catch (wsErr) {
      console.error('[Internal] WS broadcast error:', wsErr);
    }

    // 4. Send Expo push notifications for offline/background users
    let pushed = 0;
    try {
      await sendSignalPushNotifications(signalForClients);
      pushed = 1;
      console.log(`[Internal] Push notifications sent for signal: ${signalId}`);
    } catch (pushErr) {
      console.error('[Internal] Push notification error:', pushErr);
    }

    return reply.send({ signal: signalForClients, pushed });
  });

  // ── GET /internal/health ────────────────────────────────────

  fastify.get('/internal/health', async (_req: FastifyRequest, reply: FastifyReply) => {
    return reply.send({
      status:    'ok',
      service:   'smc-api-server',
      timestamp: Date.now(),
    });
  });
}